### ISSUE TITLE
Re-implement repo patches

### ISSUE THREAD

**Issue by iartemenko** [xen-troops/meta-xt-images#143]
Patches for bitbake fetch2 should be re-implemented while migrating to Yocto-thud in order to codebase changes in repo.py. The reason is https://github.com/xen-troops/manifests/pull/69

**Comment by rshym** [comment]
Patches for fetcher2/repo are not needed anymore after move of android to upper yocto.
Issue is not relevant anymore.

**Comment by rshym** [comment]
Issue is not relevant anymore.
