### ISSUE TITLE
Please move product specific bbappend out to product

### ISSUE THREAD

**Issue by andr2000** [xen-troops/meta-xt-images#28]
meta-xt-images/recipes-domx/meta-xt-images-domx/recipes-graphics/wayland/weston_1.11.0.bbappend
is a product specific append and must be inside the product which uses it.
Please move to prod-devel, but also consult @aanisov if this is really needed

**Comment by aanisov** [comment]
That bbappend sets `idle-time=0` in order to disable screen locking in weston. Please consider for yourself if this functionality is needed for the projects.

**Comment by andr2000** [comment]
it is conflicting with AGL at least

**Comment by iartemenko** [comment]
Fixed in: 855a9dcc8edf02e225074cc499d730d14f1f55f6
